In [13]:
import numpy as np 
import pandas as pd
import geopandas

# time series

In [2]:
df=pd.read_excel("data/vaccinations-by-manufacturer-with-vaccine-efficacy-KM.xlsx")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Protection from Ancestral var,Unnamed: 5,Protection from Alpha var,Unnamed: 7,Protection from Beta var,Beta,Protection from Gamma var,Gamma,Protection from Delta var,Delta,Protection from Omicron var,Omicron
0,Country,Date,Vaccine_Manufacturer,Total_Vaccinations,Severe Disease,Infection,Severe Disease,Infection,Severe Disease,Infection,Severe Disease,Infection,Severe Disease,Infection,Severe Disease,Infection
1,Argentina,2020-12-29 00:00:00,Oxford/AstraZeneca,1,0.94,0.63,0.94,0.63,0.94,0.69,0.94,0.69,0.94,0.69,0.71,0.36
2,Argentina,2020-12-29 00:00:00,Sinopharm/Beijing,1,0.73,0.68,0.73,0.68,0.71,0.67,0.71,0.67,0.71,0.67,0.53,0.35
3,Argentina,2020-12-29 00:00:00,Sputnik V,20488,18848.96,17619.68,18848.96,17619.68,18234.32,17414.8,18234.32,17414.8,18234.32,17414.8,11268.4,7375.68
4,Argentina,2020-12-30 00:00:00,Sputnik V,40590,37342.8,34907.4,37342.8,34907.4,36125.1,34501.5,36125.1,34501.5,36125.1,34501.5,22324.5,14612.4

# statistics

In [15]:
world = geopandas.read_file(
        geopandas.datasets.get_path('naturalearth_lowres'))
world.rename(columns={'iso_a3': 'ISO3'}, inplace=True)
world['gdp_per_cap'] = world.gdp_md_est / world.pop_est
world.head()

,pop_est,continent,name,ISO3,gdp_md_est,geometry,gdp_per_cap
0,889953.0,Oceania,Fiji,FJI,5496,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",0.006176
1,58005463.0,Africa,Tanzania,TZA,63177,"POLYGON ((33.90371 -0.95000, 34.07262 -1.05982...",0.001089
2,603253.0,Africa,W. Sahara,ESH,907,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948...",0.001504
3,37589262.0,North America,Canada,CAN,1736425,"MULTIPOLYGON (((-122.84000 49.00000, -122.9742...",0.046195
4,328239523.0,North America,United States of America,USA,21433226,"MULTIPOLYGON (((-122.84000 49.00000, -120.0000...",0.065298

In [11]:
df_vaccine=pd.read_excel('data/vaccination-data-WHO-12-28-2022-NO-DETAILS for-vaciinetype-date.xlsx')
df_vaccine.isnull().sum()
df_vaccine=df_vaccine[df_vaccine["COUNTRY"]!="Eritrea"]
np.sum(df_vaccine["TOTAL_VACCINATIONS"])/1000000000

13.073712554

In [23]:
world["Total_Vaccinations"] = np.nan
world['vaccines'] = np.nan
world["Persons_Fully_Vaccinated"] = np.nan
world["persons_vaccinated"] = np.nan

for i in range(world.shape[0]):
    iso_code = world.loc[i]["ISO3"]
    if iso_code in list(df_vaccine["ISO3"]):
        world.at[i, "Total_Vaccinations"] = df_vaccine[df_vaccine["ISO3"]
                                                       == iso_code].iloc[0]["TOTAL_VACCINATIONS"]
        world.at[i, "vaccines"] = df_vaccine[df_vaccine["ISO3"]
                                             == iso_code].iloc[0]["VACCINES_USED"]
        world.at[i, "Persons_Fully_Vaccinated"] = df_vaccine[df_vaccine["ISO3"]
                                                             == iso_code].iloc[0]["PERSONS_FULLY_VACCINATED"]
        world.at[i, "persons_vaccinated"] = df_vaccine[df_vaccine["ISO3"]
                                                       == iso_code].iloc[0]["PERSONS_VACCINATED_1PLUS_DOSE"]

world_notnull=world[world["Total_Vaccinations"].notnull()]
total_pop=np.sum(world_notnull["pop_est"])
world_notnull["Persons_Fully_Vaccinated"].sum()/total_pop
world_notnull["persons_vaccinated"].sum()/total_pop

0.7190074853141382